version: "3.8"

services:
  db:
    container_name: db
    build:
      context: ./postgres
    ports:
      - "5432:5432" 
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "3001:3001"  
    environment:
      PGUSER: test
      PGPASSWORD: test
      PGDATABASE: employees
      PGHOST: db
      PGPORT: 5432
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000" 
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
